version: 1.0.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: cloudinsight-dotnet-sdk.*.nupkg
  name: NuGet Package
cache:
- packages -> **\packages.config
